# Generated by Django 5.2.11 on 2026-02-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
