# Generated by Django 5.2.11 on 2026-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_assignment'),
        ('users', '0003_alter_profile_profile_pix'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'booked_at'], name='hospital_ap_status_ff9acd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='hospital_ap_patient_e7914f_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status'], name='hospital_ap_doctor__5a6fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['booked_at'], name='hospital_ap_booked__324b58_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['published', '-published_date'], name='hospital_bl_publish_27edb6_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='hospital_bl_slug_cbd7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', 'published'], name='hospital_bl_author__1c3b40_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-created_at'], name='hospital_bl_created_2b93ea_idx'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['status', 'created_at'], name='hospital_te_status_97338a_idx'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['appointment', 'status'], name='hospital_te_appoint_3eab2f_idx'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='hospital_te_assigne_07173f_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalrequest',
            index=models.Index(fields=['status', 'created_at'], name='hospital_vi_status_005560_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalrequest',
            index=models.Index(fields=['appointment', 'status'], name='hospital_vi_appoint_7a270c_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalrequest',
            index=models.Index(fields=['assigned_to', 'status'], name='hospital_vi_assigne_4e84c6_idx'),
        ),
    ]
