# Generated by Django 5.2.5 on 2026-03-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_add_performance_indexes'),
        ('users', '0004_alter_profile_profile_pix'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', '-booked_at'], name='hospital_ap_patient_6b2f88_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', '-booked_at'], name='hospital_ap_doctor__7069b0_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title'], name='hospital_bl_title_a4754e_idx'),
        ),
        migrations.AddIndex(
            model_name='testrequest',
            index=models.Index(fields=['appointment', '-created_at'], name='hospital_te_appoint_9ca42e_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalrequest',
            index=models.Index(fields=['appointment', '-created_at'], name='hospital_vi_appoint_0ce130_idx'),
        ),
    ]
